function envInt(key: string, fallback: number): number {
  const v = process.env[key];
  if (v === undefined) return fallback;
  const parsed = Number.parseInt(v, 10);
  return Number.isNaN(parsed) ? fallback : parsed;
}

export const CONFIG = {
  GIT_COMMAND_TIMEOUT_MS: envInt("GIT_COMMAND_TIMEOUT_MS", 5_000),
  GIT_CLONE_TIMEOUT_MS: envInt("GIT_CLONE_TIMEOUT_MS", 10_000),
  GIT_LONG_OP_TIMEOUT_MS: envInt("GIT_LONG_OP_TIMEOUT_MS", 300_000),
  PROCESS_KILL_TIMEOUT_MS: envInt("PROCESS_KILL_TIMEOUT_MS", 5_000),
  PROCESS_PS_TIMEOUT_MS: envInt("PROCESS_PS_TIMEOUT_MS", 5_000),
  TOKEN_REFRESH_TIMEOUT_MS: envInt("TOKEN_REFRESH_TIMEOUT_MS", 10_000),
  KEEPALIVE_INTERVAL_MS: envInt("KEEPALIVE_INTERVAL_MS", 60_000),
  MEMORY_MONITOR_INTERVAL_MS: envInt("MEMORY_MONITOR_INTERVAL_MS", 60_000),
  TOKEN_REFRESH_INTERVAL_MS: envInt("TOKEN_REFRESH_INTERVAL_MS", 3_600_000),
  GCS_SYNC_INTERVAL_MS: envInt("GCS_SYNC_INTERVAL_MS", 300_000),
  DEBOUNCE_MS: envInt("DEBOUNCE_MS", 5_000),
  KILLSWITCH_POLL_INTERVAL_MS: envInt("KILLSWITCH_POLL_INTERVAL_MS", 10_000),
  WORKTREE_GC_INTERVAL_MS: envInt("WORKTREE_GC_INTERVAL_MS", 600_000),
  SSE_HEARTBEAT_INTERVAL_MS: envInt("SSE_HEARTBEAT_INTERVAL_MS", 15_000),
  DELIVERY_SETTLE_MS: envInt("DELIVERY_SETTLE_MS", 250),
  AGENT_POLL_INTERVAL_MS: envInt("AGENT_POLL_INTERVAL_MS", 5_000),
  GRADES_POLL_INTERVAL_MS: envInt("GRADES_POLL_INTERVAL_MS", 10_000),
  TASKS_POLL_INTERVAL_MS: envInt("TASKS_POLL_INTERVAL_MS", 5_000),
  COST_POLL_INTERVAL_MS: envInt("COST_POLL_INTERVAL_MS", 10_000),
  GRAPH_POLL_INTERVAL_MS: envInt("GRAPH_POLL_INTERVAL_MS", 5_000),
  KILLSWITCH_UI_POLL_INTERVAL_MS: envInt("KILLSWITCH_UI_POLL_INTERVAL_MS", 5_000),
  MAX_MESSAGE_LENGTH: envInt("MAX_MESSAGE_LENGTH", 50_000),
  MAX_BATCH_MESSAGE_SIZE: envInt("MAX_BATCH_MESSAGE_SIZE", 20),
  AGENT_UPLOAD_LIMIT: process.env.AGENT_UPLOAD_LIMIT ?? "10mb",
  JSON_BODY_LIMIT: process.env.JSON_BODY_LIMIT ?? "1mb",
  MAX_ACTIVE_TASKS: envInt("MAX_ACTIVE_TASKS", 10_000),
  MAX_TASK_DEPENDENCIES: envInt("MAX_TASK_DEPENDENCIES", 100),
  MAX_TASK_RETRIES: envInt("MAX_TASK_RETRIES", 10),
  MAX_TASK_TIMEOUT_MS: envInt("MAX_TASK_TIMEOUT_MS", 3_600_000),
  MIN_TASK_TIMEOUT_MS: envInt("MIN_TASK_TIMEOUT_MS", 10_000),
  RATE_LIMIT_REQUESTS_PER_MINUTE: envInt("RATE_LIMIT_REQUESTS_PER_MINUTE", 120),
  RATE_LIMIT_REFILL_INTERVAL_MS: envInt("RATE_LIMIT_REFILL_INTERVAL_MS", 60_000),
  AUTO_PAUSE_DEBOUNCE_MS: envInt("AUTO_PAUSE_DEBOUNCE_MS", 10_000),
  MAX_PERSISTED_EVENTS: envInt("MAX_PERSISTED_EVENTS", 5_000),
  EVENT_FILE_TRUNCATE_THRESHOLD: envInt("EVENT_FILE_TRUNCATE_THRESHOLD", 10_000),
  EVENT_RING_BUFFER_SIZE: envInt("EVENT_RING_BUFFER_SIZE", 1_000),
  MAX_MESSAGES_IN_MEMORY: envInt("MAX_MESSAGES_IN_MEMORY", 500),
  MAX_EVENT_LOG_ENTRIES: envInt("MAX_EVENT_LOG_ENTRIES", 500),
  MAX_LOG_STRING_LENGTH: envInt("MAX_LOG_STRING_LENGTH", 1_000),
  MAX_TOOL_RESULT_BYTES: envInt("MAX_TOOL_RESULT_BYTES", 16_384),
  MEMORY_LIMIT_BYTES: envInt("MEMORY_LIMIT_BYTES", 34_359_738_368),
  MEMORY_WARN_THRESHOLD: Number(process.env.MEMORY_WARN_THRESHOLD ?? "0.75"),
  MEMORY_REJECT_THRESHOLD: Number(process.env.MEMORY_REJECT_THRESHOLD ?? "0.85"),
  DEFAULT_MAX_PROMPT_LENGTH: envInt("DEFAULT_MAX_PROMPT_LENGTH", 100_000),
  DEFAULT_MAX_TURNS: envInt("DEFAULT_MAX_TURNS", 500),
  DEFAULT_MAX_AGENTS: envInt("DEFAULT_MAX_AGENTS", 100),
  DEFAULT_MAX_BATCH_SIZE: envInt("DEFAULT_MAX_BATCH_SIZE", 10),
  DEFAULT_SESSION_TTL_MS: envInt("DEFAULT_SESSION_TTL_MS", 14_400_000),
  DEFAULT_MAX_AGENT_DEPTH: envInt("DEFAULT_MAX_AGENT_DEPTH", 3),
  DEFAULT_MAX_CHILDREN_PER_AGENT: envInt("DEFAULT_MAX_CHILDREN_PER_AGENT", 20),
} as const;

export function getConfig<K extends keyof typeof CONFIG>(key: K): (typeof CONFIG)[K] {
  return CONFIG[key];
}

export const MAX_PERSISTED_EVENTS = CONFIG.MAX_PERSISTED_EVENTS;
export const EVENT_FILE_TRUNCATE_THRESHOLD = CONFIG.EVENT_FILE_TRUNCATE_THRESHOLD;
export const EVENT_RING_BUFFER_SIZE = CONFIG.EVENT_RING_BUFFER_SIZE;
export const AGENT_DEDUP_WINDOW_MS = envInt("AM_AGENT_DEDUP_WINDOW_MS", 10_000);
export const PAUSED_TTL_MS = envInt("AM_PAUSED_TTL_MS", 24 * 60 * 60 * 1000);
export const STANDBY_MAX_TTL_MS = envInt("AM_STANDBY_MAX_TTL_MS", 2 * 60 * 60 * 1000);
export const PROMPT_NAME_MAX_INPUT = envInt("AM_PROMPT_NAME_MAX_INPUT", 120);
export const PROMPT_NAME_MAX_SLUG = envInt("AM_PROMPT_NAME_MAX_SLUG", 40);
export const MAX_MESSAGES = envInt("AM_MAX_MESSAGES", 500);
export const MAX_RESTORE_MESSAGES = envInt("AM_MAX_RESTORE_MESSAGES", 500);
export const MAX_MESSAGE_AGE_MS = envInt("AM_MAX_MESSAGE_AGE_MS", 15 * 60 * 1000);
export const MAX_SSE_CONNECTIONS = envInt("AM_MAX_SSE_CONNECTIONS", 100);
export const SSE_BACKPRESSURE_BYTES = envInt("AM_SSE_BACKPRESSURE_BYTES", 1_048_576);
export const SAVE_DEBOUNCE_MS = envInt("AM_SAVE_DEBOUNCE_MS", 500);
export const ORCHESTRATOR_MAX_RETRIES = envInt("AM_ORCHESTRATOR_MAX_RETRIES", 3);
export const ORCHESTRATOR_POLL_INTERVAL_MS = envInt("AM_ORCHESTRATOR_POLL_MS", 5_000);
export const ORCHESTRATOR_MAX_ASSIGNMENTS = envInt("AM_ORCHESTRATOR_MAX_ASSIGNMENTS", 5);
export const MAX_LOG_STRING_LENGTH = envInt("AM_MAX_LOG_STRING_LENGTH", 500);
export const MAX_EVENT_LOG = envInt("AM_MAX_EVENT_LOG", 1000);
